id: P006680
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:15:33.016283
source_metadata:
  id: bdr:W1AC220
  title: 'དྭགས་པོ་ཐར་རྒྱན། '
  author: ''
  volumes:
    88c1d4ac86a245fbbb64f61708c960d1:
      image_group_id: I4PD4471
      title: ''
      volume_number: 1
      total_pages: 470
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
